openapi: 3.0.0
info:
  title: Clean Architecture Blog API
  version: 1.0.0
paths:
  /api/articles:
    get:
      summary: Retrieve a list of articles
      security:
        - bearerAuth: []
      responses:
        200:
          description: A list of articles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    content:
                      type: string
    post:
      summary: Create a new article
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                author:
                  type: string
      responses:
        201:
          description: Article created successfully
  /api/articles/{id}:
    get:
      summary: Retrieve a single article by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The article ID
      responses:
        200:
          description: A single article
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  content:
                    type: string
    delete:
      summary: Delete an article by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The article ID
      responses:
        200:
          description: Article deleted successfully
    put:
      summary: Update an existing article
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                title:
                  type: string
                content:
                  type: string
                author:
                  type: string
      responses:
        200:
          description: Article updated successfully
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
